### ISSUE TITLE
Support for syscalls

### ISSUE THREAD

**Issue by Maijin** [wargio/r2dec-js#102]
Support for syscalls (int 0x80, syscall etc.) - make sure you don't reimplement the syscalls, they are already available in radare2 with `as` command and can already be resolved with e asm.emu/e asm.emuwrite.

**Comment by Maijin** [comment]
Also this is supported by pdc already

**Comment by wargio** [comment]
do you have any example?

**Comment by wargio** [comment]
ok, i'll try to fix this asap.

**Comment by wargio** [comment]
Fixed in https://github.com/wargio/r2dec-js/commit/51424c49cd2d42824af0af51a7c1f4a872760b69
