### ISSUE TITLE
Duktape lacks many of ES5/6 fundamental features

### ISSUE THREAD

**Issue by elicn** [wargio/r2dec-js#119]
A partial list of such features:
- Default function argument value
- Keyword `let`
- Keywords used for iterators: `yield`, `yield*`, `function*`
- Arrow functions `=>`
- Ellipsis arguments unpacking
- `Array.from`
- `Array.prototype.find`
- `Map` object
- `Set` object
- and many others...

It is suggested to bolster Duktape with polyfills to gain at least some of those features.
Two possible candidates could be: [es6-shim](https://github.com/paulmillr/es6-shim) and [core-js](https://github.com/zloirock/core-js). While es6-shim looks minimal and slim, core-js seems to be heavier but much more comprehensive and gets updated and fixed more frequently.

**Comment by XVilka** [comment]
Why not link corresponding duktape bugs here, so it will be easier to track
the progress?

**Comment by elicn** [comment]
The purpose of this issue is not improving `Duktape` [which improves quite slowly], but to improve `r2dec`. If we want those features to be available in r2dec, we'll probably have to "import" them from somewhere else.

**Comment by XVilka** [comment]
Why not both? It is always win-win.

**Comment by trufae** [comment]
I think this ticket can be closed now

**Comment by elicn** [comment]
A blast from the past..!
