### ISSUE TITLE
Error on installation of r2dec

### ISSUE THREAD

**Issue by AmiZya** [wargio/r2dec-js#122]
Hello,

I got the following error when I run `r2pm install r2dec` 

> cc -I/Users/amine/.local/share/radare2/prefix/include -g -O3 -I/usr/local/Cellar/radare2/2.8.0/include/libr -I/usr/local/Cellar/openssl/1.0.2p/include -I/usr/local/Cellar/radare2/2.8.0/include/libr -I./duktape -L/Users/amine/.local/share/radare2/prefix/lib -L/usr/local/Cellar/radare2/2.8.0/lib -L/usr/local/Cellar/openssl/1.0.2p/lib -L/usr/local/Cellar/radare2/2.8.0/lib -lr_core -lssl -lcrypto -lr_config -lr_debug -lr_bin -lr_anal -lr_bp -lr_egg -lr_asm -lr_lang -lr_parse -lr_flag -lr_cons -lr_reg -lr_search -lr_syscall -lr_fs -lr_io -lr_socket -lr_magic -lr_crypto -lr_hash -lr_util -ldl -lm -std=c99 -shared -fPIC duktape/duktape.c duktape/duk_console.c core_pdd.c -o core_pdd.dylib
> ld: warning: directory not found for option '-L/Users/amine/.local/share/radare2/prefix/lib'
> make install
> mkdir -p
> usage: mkdir [-pv] [-m mode] directory ...
> make[1]: *** [install] Error 64
> make: *** [all] Error 2

**Comment by wargio** [comment]
Seems there is a mismatch between r2dec and your r2 version.
