### ISSUE TITLE
Conditionals doesnt appear in the disasm or the graph

### ISSUE THREAD

**Issue by radare** [wargio/r2dec-js#143]
<img width="986" alt="screenshot 2019-03-05 at 00 37 53" src="https://user-images.githubusercontent.com/917142/53770327-fbd1c000-3ede-11e9-94c6-92915e470beb.png">
<img width="1406" alt="screenshot 2019-03-05 at 00 38 40" src="https://user-images.githubusercontent.com/917142/53770343-08eeaf00-3edf-11e9-8ca7-abc12531e575.png">

**Comment by wargio** [comment]
fixed with https://github.com/wargio/r2dec-js/commit/d758e99e23bfd96e90ea2dea94d829bee6ccb959
