### ISSUE TITLE
        __asm ("blo 0x488c"); is not supported

### ISSUE THREAD

**Issue by radare** [wargio/r2dec-js#144]
[issue.json.zip](https://github.com/wargio/r2dec-js/files/2928777/issue.json.zip)

<img width="506" alt="screenshot 2019-03-05 at 01 46 34" src="https://user-images.githubusercontent.com/917142/53772916-84a12980-3ee8-11e9-81d3-aaaf0c37cb6f.png">

**Comment by wargio** [comment]
fixed with https://github.com/wargio/r2dec-js/commit/d758e99e23bfd96e90ea2dea94d829bee6ccb959
