### ISSUE TITLE
Strings passed to variables (var_) aren't substituted

### ISSUE THREAD

**Issue by Maijin** [wargio/r2dec-js#179]
Strings passed to variables aren't substituted. Example in this binary:

[ch2.bin.zip](https://github.com/wargio/r2dec-js/files/3413441/ch2.bin.zip)

Current Behaviour:

```
    var_ch = str.john;
    var_10h = str.the_ripper;
```

Expected Behaviour:

```
    var_ch = "john;
    var_10h = "the ripper";
```

pddi - [pddi.txt](https://github.com/wargio/r2dec-js/files/3413443/pddi.txt)

**Comment by wargio** [comment]
ok, i have found the main issue with this. for some reasons, r2 didn't populate the ptr value. i can fix this on r2dec side, but maybe should be fixed also on r2 side.
