### ISSUE TITLE
background coloring

### ISSUE THREAD

**Issue by imyxh** [wargio/r2dec-js#183]
So I think I've figured out that when r2dec displays inline assembly output, it's colored with the foreground color of "usrcmt" as set by the radare2 theme.

With many themes, this looks just fine. But with some, like the built-in *bold* and *ogray* themes, usrcmt is meant to be dark on light:

```
ec usrcmt rgb:000 rgb:f72  # from ogray
```

Of course, on dark terminals this means that the text will be pretty much invisible, since the f72 background is dropped.

![image](https://user-images.githubusercontent.com/12703838/62085432-5eba4f80-b210-11e9-8c56-26474915ac68.png)

This could be fixed by just honoring the theme's choice of background color.

But tangentially, why does r2dec even use the usrcmt color for inline assembly, anyway? The usrcmt style is for user-defined comments, which are assumed to be fairly sparse in the disassembly view. It makes sense for themes to assign really obnoxious colors to usrcmt so that the few comments there are will stand out. Conversely, r2dec spits out a *lot* of assembly, and for many themes would look really ugly if the background colors of usrcmt were ported properly.

I think r2dec should really use another color key other than usrcmt for assembly code. Perhaps use "other"? I can move this to another issue if you like.

**Comment by wargio** [comment]
there are 2 ways to fix this:
Fix 1 (which does not require me to touch code): create a theme manually and define it via `r2dec.theme`, see [defailt.json](https://github.com/wargio/r2dec-js/blob/master/themes/default.json).
Fix 2 (requires a patch): handle background color.

Besides those fixes, can you produce an issue via `pddi` of that x86 code so i can add the missing assembly instructions?

**Comment by imyxh** [comment]
Aha. Looks like the missing assembly instructions are because I'm using AT&T syntax. #184

I would've gladly defined my own theme except I couldn't actually find a setting for the colors of inline assembly in the default.json file.

**Comment by wargio** [comment]
it's the string color one.

**Comment by imyxh** [comment]
Ah, so "text". Works for me, thanks!
