### ISSUE TITLE
support asm.syntax=att

### ISSUE THREAD

**Issue by imyxh** [wargio/r2dec-js#184]
I've been using radare2 with GAS/AT&T syntax for a long time, and I just realized that r2dec is much more effective at decompiling when asm.syntax=intel.

**asm.syntax=intel:**
```c
/* r2dec pseudo code output */
/* be-quick-or-be-dead-1 @ 0x400706 */
#include <stdint.h>
 
int32_t calculate_key (void) {
    uint32_t var_4h;
    var_4h = 0x75c3328b;
    do {
        var_4h++;
    } while (var_4h != 0xeb866516);
    eax = var_4h;
    return eax;
}
```

**asm.syntax=att:**
```c
/* r2dec pseudo code output */
/* be-quick-or-be-dead-1 @ 0x400706 */
#include <stdint.h>
 
void calculate_key (void) {
    uint32_t var_4h;
    __asm ("pushq %rbp");
    %rsp = %rbp;
    __asm ("movl $0x75c3328b, var_4h");
    do {
        __asm ("addl $1, var_4h");
        __asm ("cmpl $0xeb866516, var_4h");
    } while (? != ?);
    __asm ("movl var_4h, %eax");
    __asm ("popq %rbp");
    __asm ("retq");
}
```

This is pretty much a duplicate of #4 except that was closed a long time ago with fixes for everything but AT&T syntax.

I think the easiest solution I can think of is to check if `asm.syntax` is set to something other than Intel, and if so, quickly switch it right before the disassembly is done, then switch it back when pdd returns. I can start looking into the r2dec source code to see how manageable this would be.

**Comment by radare** [comment]
R2dec should force intel syntax and implement the missing instructions if any

**Comment by wargio** [comment]
yes, i do, i just do not handle those instructions.

**Comment by wargio** [comment]
fixed with https://github.com/wargio/r2dec-js/commit/200782686a4d78d71015871c5ec93ad73e951833

**Comment by imyxh** [comment]
Oof, now I have to set my radare2 back to att syntax every time I run pdd....

**Comment by wargio** [comment]
wait, maybe i did something stupid. let me check.

**Comment by wargio** [comment]
i've fixed it. i did something retarded and used the value as boolean instead of a string. now it should work as expected.
