### ISSUE TITLE
feature request - highlighting current offset

### ISSUE THREAD

**Issue by s0i37** [wargio/r2dec-js#187]
Good day.
I wanna suggest a tiny improvement - to highlight line/lines respects current offset in current function.
For example in "V" mode we can add "cmd.cprompt=pdd" and then use "c" cursor mode.
Thank you.

**Comment by wargio** [comment]
wait, i didn't get this.
You would like to have the equivalent of Visual mode but without visual?
like with a comment or just color highlight?

**Comment by s0i37** [comment]
I mean just highlighting of current line (background)
It seems it can be easy to implement. r2dec provide information about relation between instruction <--> line of pseudo code.

**Comment by wargio** [comment]
let me try

**Comment by wargio** [comment]
![image](https://user-images.githubusercontent.com/561184/62866073-4b2ede80-bd10-11e9-9a43-67a6643a54a7.png)
What about this?

**Comment by s0i37** [comment]
Looks great. But may be it needs to put "\x1b[49m" on every line end?

**Comment by s0i37** [comment]
BTW, may be it is possible to implement highlighting pseudo code lines when used selecting mode `Vc`+SHIFT?
![temp](https://user-images.githubusercontent.com/22872513/62928706-7da11000-bdd2-11e9-9aa2-ee60ea9318cb.png)

**Comment by wargio** [comment]
that's r2,  not r2dec. can you open an issue on r2 issues?

**Comment by s0i37** [comment]
Why r2?
Or you mean what r2 doesn't provide info about selection ranges?

**Comment by wargio** [comment]
because that's something i cannot code. it's r2 handling the bytes highlight there

**Comment by radare** [comment]
You may disable scr.highlight in your side

**Comment by wargio** [comment]
@radare should I? What would happen if I don't?

**Comment by s0i37** [comment]
It seems works good. But why `r2dec` doesn't highlight lines in cursor mode?
![temp](https://user-images.githubusercontent.com/22872513/62996827-a03d3280-be7f-11e9-86f8-b2a81a118b98.png)

**Comment by radare** [comment]
Because thats not how things work . Use panels mode , use pddo and click on offsets instead

**Comment by s0i37** [comment]
Is it require `scr.wheel` ?

**Comment by radare** [comment]
Yes

**Comment by s0i37** [comment]
Is it may to implement?

**Comment by radare** [comment]
e scr.highlight= offset

**Comment by s0i37** [comment]
No I mean current offset.
`pdd` highlights current offset `s`.
`scr.highlight` is `r2` highlighting not `r2dec`

**Comment by radare** [comment]
Scr.highlights affects everything thrown via rcons and it works in panels

**Comment by s0i37** [comment]
No I mean another or I don't understand something...
I just want that cursor mode changes offset in `cmd.vprompt`, `cmd.cprompt` and `pg` like a `v:`
If so r2dec will highlights pseudocode without scrolling disasm. `pddo` + `e scr.highlight=0xADDR` is a bit less convenient in my humple opinion...

**Comment by s0i37** [comment]
What if r2dec will obtaint current offset through "?v $O" instead of "s"?
In this case r2dec could highlighs current offset even in cursor-mode.
![temp](https://user-images.githubusercontent.com/22872513/70984957-2f33b300-20dd-11ea-934b-09a56f86092e.png)
Without cursor mode "$O" variable fully matches with "s"

**Comment by wargio** [comment]
yes it is possible to add this.

**Comment by s0i37** [comment]
Yes, add this please.
