### ISSUE TITLE
fatal error: 'r_cons.h' file not found

### ISSUE THREAD

**Issue by umasii** [wargio/r2dec-js#232]
**Describe the bug**
When I run "r2pm -i r2dec" my terminal produces the following:

```Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Install Done For r2dec
make: pkg-config: Command not found
[CC] duktape/duktape.o
make: pkg-config: Command not found
[CC] duktape/duk_console.o
duktape/duk_console.c:13:10: fatal error: 'r_cons.h' file not found
#include <r_cons.h>
         ^~~~~~~~~~
1 error generated.
make: *** [duktape/duk_console.o] Error 1
```
I've tried both reinstalling r2, as that was the fix for another user, and running "sudo apt install pkg-config", which produces the error 

```
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/apt" (-1)
```
Any help is greatly appreciated!

**Component**
- [x] core
- [ ] arm
- [ ] avr
- [ ] m68k
- [ ] mips
- [ ] ppc
- [ ] sparc
- [ ] v850
- [ ] wasm
- [ ] x86-64

**Comment by wargio** [comment]
use radare2 from git, not the one from the package manager.

**Comment by wargio** [comment]
also you need to install `pkg-config` which is the main cause here.

**Comment by umasii** [comment]
Thanks for the response! r2 was installed via 
```
git clone https://github.com/radareorg/radare2.git
```

and when I try to install ```pkg-config``` it gives the error in my first post. Sorry for the hassle.

**Comment by wargio** [comment]
i guess cloning from the git repo and following the instruction in the readme. i strongly advise you to read the manual in this case.
