### ISSUE TITLE
Proposal: Hide the endbr64 instruction

### ISSUE THREAD

**Issue by trufae** [wargio/r2dec-js#254]
**Describe the bug**

When decompiling functions containing instructions like `endbr64`, those should be ignored/skipped and not displayed, like if it was a `nop`

![Screenshot 2021-10-19 at 22 15 09](https://user-images.githubusercontent.com/6431515/137983822-37ff496f-dd60-4099-8630-f74615594be5.png)

**Component**
- [ ] core
- [ ] arm
- [ ] avr
- [ ] m68k
- [ ] mips
- [ ] ppc
- [ ] sparc
- [ ] v850
- [ ] wasm
- [x] x86-64

**Reproduce via JSON (pddi)**

The screenshot is taken from the CI

**Comment by wargio** [comment]
nopped
