### ISSUE TITLE
pddl do not analyse all func

### ISSUE THREAD

**Issue by oditynet** [wargio/r2dec-js#281]
radare2 show me codes of my programe:
```
...
0x55ed9d71f15e      e80d030000     call 0x55ed9d71f470
...
```
if i will press button 'S' in radare2 then go to func 0x55ed9d71f470
but r2dec in func 0x55ed9d71f470 show me:
> pdd
Error: no data available.
Please analyze the function/binary first.

what is that? r2rec not see a lot of codes at my program. (pddf do not see a lot of code my programe too)

**Comment by wargio** [comment]
I do not know what is specifically wrong but if it shows ` Error: no data available.` means that r2 did not analyze that offset. you can manually do this by doing `af @ 0x55ed9d71f470`
