### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by trufae** [wargio/r2dec-js#288]
Last release was around the 5.7.x seasson, and the last commit is fixing a crash that affects 5.8.x, having a new release will solve that.

thanks

**Comment by wargio** [comment]
oh, sorry, let me do this asap.

**Comment by wargio** [comment]
https://github.com/wargio/r2dec-js/releases/tag/5.8.8

**Comment by trufae** [comment]
Why its not shown as the last release in the main page?

**Comment by wargio** [comment]
fixed.
