### ISSUE TITLE
radare2: symbol lookup error: /root/.local/share/radare2/plugins/core_pdd.so: undefined symbol: r_cons_strcat

### ISSUE THREAD

**Issue by OscarAbundez23** [wargio/r2dec-js#292]
Everytime I try to use r2dec with any of the pdd subcommands, radare2 crashes and shows me this error `radare2: symbol lookup error: /root/.local/share/radare2/plugins/core_pdd.so: undefined symbol: r_cons_strcat`

**Comment by wargio** [comment]
did you rebuild the plugin?

**Comment by wargio** [comment]
@trufae did you remove `r_cons_strcat` ? can i use `r_cons_println` ?

**Comment by OscarAbundez23** [comment]
Rebuild? I don't know haha, I just installed it with `r2pm -i r2dec`, I don't know if it has anything to do with the fact that I am using it on a docker container

**Comment by wargio** [comment]
yes, you need to rebuild it via r2pm

**Comment by OscarAbundez23** [comment]
Ok, sorry, I didn't know that, but there is no information on the installation and usage. And sorry again but,  how I rebuild that? Should I reinstall r2?

**Comment by wargio** [comment]
The installation/usage issue should be brought on r2pm/r2 itself, since this usually happens when you update r2.
just try to see what `r2pm -h` says. probably `r2pm -i r2dec` should be enough to rebuild r2dec.
That said, is possible that pancake has removed `r_cons_strcat` so i might still need to do some changes.

**Comment by OscarAbundez23** [comment]
Ooohh haha, ok, yes I had already tried to reinstall r2dec before with `r2pm -i r2dec` so I think maybe it needs some changes as you said

**Comment by trufae** [comment]
Yes, RCons.strcat was a very bad name, it's now RCons.print, but i decided to push few defines for backward compat and mark those apis as deprecated for r2-6.0.0, it should build now

**Comment by OscarAbundez23** [comment]
Ok, It works now, thank you very much
