### ISSUE TITLE
Remove duktape references in the DEVELOPERS doc

### ISSUE THREAD

**Issue by trufae** [wargio/r2dec-js#302]
* https://github.com/wargio/r2dec-js/blob/master/DEVELOPERS.md

now that r2dec runs on qjs i think its worth updating this file accordingly.

Also, worth mentioning `r2dec.debug` var and this oneliner which is the one i used to test changes (because the JS code is now always compiled inside the plugin) <- this oneliner can be improved quite a lot :P 

`1$ rm -rf b ; meson b ; ninja -C b install`

**Comment by wargio** [comment]
oh yeah, i forgot to update the readme. i actually delete the header file to always recompile the file.

**Comment by wargio** [comment]
Now the js code is always rebuilt. no need to use that oneliner or my workaround.
