### ISSUE TITLE
Looks like meson on Windows expects an absolute path

### ISSUE THREAD

**Issue by Arazare** [wargio/r2dec-js#306]
Hey guys, I am trying to setup all of this things on Windows 11. I am using Chocolatey to have all of the packages in the PATH.
Here is the list of problems I have:

1. Trying to install r2dec directly from from radare2 cmd
![image](https://github.com/wargio/r2dec-js/assets/165500655/e34b47f6-e3bc-4268-a940-b778377ea244)

2. It's when I try to use meson to build it on my own:
![image](https://github.com/wargio/r2dec-js/assets/165500655/59bb1305-73d8-43b7-a15c-c12399d9e805)

I've also attached a messon_log.txt file:
[meson-log.txt](https://github.com/wargio/r2dec-js/files/14812703/meson-log.txt)

I'm not that "techy", so I maybe will need more details if I will need to do/test something

**Comment by Arazare** [comment]
![image](https://github.com/wargio/r2dec-js/assets/165500655/b0017242-d845-4146-99d4-5edba6be1d61)

As I understand "meson" is in path already

**Comment by wargio** [comment]
i think there is a bug in the script because it is trying to match with `meson"` instead of `meson`. @trufae this is invalid issue on my end.

**Comment by wargio** [comment]
Regarding building from sources manually, you need to have radare2 in the PATH, because the script uses it to find where is located.

**Comment by trufae** [comment]
The r2pm bug is fixed. It wasnt expecting a \r because the files in the git dont contain that. But git for windows makes this mess by config

**Comment by Arazare** [comment]
ye, so obvious thing... after adding radare2 to PATH everything worked.
