### ISSUE TITLE
Tag a new release for 5.9 and fix readme

### ISSUE THREAD

**Issue by trufae** [wargio/r2dec-js#307]
For packaging purposes we cant use the 5.8.8 release because it doesnr build with latest r2.

Also the readme build instructions are not correct anymore and should be updated.

thanks!

**Comment by trufae** [comment]
Also, the release tarball may include a copy of the qjs source, so it can be compiled offline

**Comment by prodrigestivill** [comment]
As a note, to pre-download the sources it can be done by running:
```
meson subprojects download
```

Later the user can use the following command to apply the changes overlay if required:
```
meson subprojects packagefiles --apply
```

**Comment by wargio** [comment]
> Also the readme build instructions are not correct anymore and should be updated.

besides `meson setup ...` what else is not valid anymore?

**Comment by prodrigestivill** [comment]
> what else is not valid anymore?

2 parts, the `cd p` and `-Djsc_folder=".."` param. since p no longer contains meson build.

**Comment by wargio** [comment]
> > what else is not valid anymore?
> 
> 2 parts, the `cd p` and `-Djsc_folder=".."` param. since p no longer contains meson build.

that was the part i was referring to.

**Comment by prodrigestivill** [comment]
Was r2dec-js 5.9.0 planned to be released as part of this issue?
Or when is expected to be released the next release?

Thanks in advance for the information.

**Comment by wargio** [comment]
sorry, i travelled in the past 2 days and i didn't have access to internet

**Comment by wargio** [comment]
https://github.com/wargio/r2dec-js/releases/tag/5.9.0

**Comment by trufae** [comment]
No hurry at all. Good to see another release out!

**Comment by prodrigestivill** [comment]
Thanks @wargio, there were no rush at all but we appreciate a lot your dedication.

Regarding the new artifact generated "src-with-deps".

I would suggest if you can remove it manually when you have time and reupload after PR #309 or similar has been merged.
