### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by trufae** [wargio/r2dec-js#324]
Looks like its taking forever to decompile the main from apple's m1 sed
```
r2 sed
af
pdd 
```

[sed.gz](https://github.com/user-attachments/files/16056852/sed.gz)

**Comment by trufae** [comment]
happening too in /bin/ls from mac in offset 0x10000541c

[ls.zip](https://github.com/user-attachments/files/16786499/ls.zip)

**Comment by trufae** [comment]
backtrace when in this infinite loop

<img width="1800" alt="Screenshot 2024-08-28 at 18 44 17" src="https://github.com/user-attachments/assets/623a4c0d-fd5a-4412-89bb-051d7109e4ca">

**Comment by trufae** [comment]
@wargio can you take a look at this issue?

**Comment by wargio** [comment]
> happening too in /bin/ls from mac in offset:
> 
>     * 0x10000541c
> 
>     * 0x100005650
> 
>     * 0x100006370
> 
> 
> [ls.zip](https://github.com/user-attachments/files/16786499/ls.zip)

This one does not occur on radare 5.9.4 (linux)
