### ISSUE TITLE
Support more r2 architectures

### ISSUE THREAD

**Issue by wargio** [wargio/r2dec-js#4]
- [x] x86 (intel)
- [ ] x86 (AT&T)
- [x] powerpc
- [x] mips
- [x] sparc
- [x] arm
- [x] arm64
- [x] avr
- [x] dalvik 

more?

**Comment by radare** [comment]
arm64 is important

**Comment by radare** [comment]
support also for dalvik can be interesting

**Comment by wargio** [comment]
added both.

**Comment by dukebarman** [comment]
x64? Or x86 is a same?

**Comment by radare** [comment]
i think x86-32 and x86-64 are already supported.

maybe is better to make a poll in twitter for this

**Comment by wargio** [comment]
no need to support AT&T
