### ISSUE TITLE
Libraries missing 

### ISSUE THREAD

**Issue by Zaper1** [wargio/r2dec-js#46]
core_pdd.c:8:10: fatal error: r_types.h: No such file or directory

do i need to install some extra libraries ?

**Comment by wargio** [comment]
those comes from r2

**Comment by wargio** [comment]
i can confirm that i don't have any issue with the r2 version from git.
What version are you using? can you also provide the OS and which command have you used to install it?

**Comment by Zaper1** [comment]
i am on kali rolling this radare2 version if from the apt repositories i got it using `apt install radare2`

**Comment by wargio** [comment]
you have to use radare2 from git; apt version is too old (for sure).
just for knowledge, what version gives you `r2 -V` ?
because mine is 
```
2.2.0-517-ge7e544cbd  r2
2.2.0-517-ge7e544cbd  r_anal
2.2.0-517-ge7e544cbd  r_lib
2.2.0-517-ge7e544cbd  r_egg
2.2.0-517-ge7e544cbd  r_asm
2.2.0-517-ge7e544cbd  r_bin
2.2.0-517-ge7e544cbd  r_cons
2.2.0-517-ge7e544cbd  r_flag
2.2.0-517-ge7e544cbd  r_core
2.2.0-517-ge7e544cbd  r_crypto
2.2.0-517-ge7e544cbd  r_bp
2.2.0-517-ge7e544cbd  r_debug
2.2.0-517-ge7e544cbd  r_hash
2.2.0-517-ge7e544cbd  r_fs
2.2.0-517-ge7e544cbd  r_io
2.2.0-517-ge7e544cbd  r_magic
2.2.0-517-ge7e544cbd  r_parse
2.2.0-517-ge7e544cbd  r_reg
2.2.0-517-ge7e544cbd  r_sign
2.2.0-517-ge7e544cbd  r_search
2.2.0-517-ge7e544cbd  r_syscall
2.2.0-517-ge7e544cbd  r_util
```

**Comment by radare** [comment]
debian split packages into many, so you have to probably install the -dev one

**Comment by Zaper1** [comment]
i reached the same conclusion it works with the git version thanks

**Comment by Zaper1** [comment]
also sorry iv'e already deleted purged the apt version

**Comment by wargio** [comment]
i'll add some info to the readme for the future.

**Comment by condret** [comment]
always use from git
