### ISSUE TITLE
Renaming variables 

### ISSUE THREAD

**Issue by Zaper1** [wargio/r2dec-js#48]
if i rename a variable in radare2 it dosn't carry into the plugin could you please make it carry over or at least add an option to manually rename it this could become a issue in large files

**Comment by radare** [comment]
R2dec should honor varnames from r2. But as long as the variable detection code is different it may be unsync :?

**Comment by wargio** [comment]
Can you make an example? i don't understand what you mean with "variable rename".

**Comment by Zaper1** [comment]
lets say im debugging a program and i find this line 
`cmp [local_var14], eax`
and i look into it and figure out that this variable holds my input so i type
`>afvn Inp`
and it changes its name however if i type pdd it will list it will not use the default name instead of the one i assigned to it

**Comment by wargio** [comment]
oh, then it's an issue with the `agj` output.
`agj` doesn't honor it. @radare

**Comment by radare** [comment]
can you fix it?

**Comment by wargio** [comment]
the issue seems to be from my side (calling `af` once more breaks things on r2)

**Comment by radare** [comment]
uhm, it shouldnt break things in r2land

**Comment by Zaper1** [comment]
well it works now that's all that matters

**Comment by radare** [comment]
it’s all that matters for r2dec but not for r2 :PPP

**Comment by Zaper1** [comment]
oh i didn't realized you are the admin of the radare repository

**Comment by radare** [comment]
also known as pancake :P

**Comment by Zaper1** [comment]
oh actually while im here can you change the default visual mode colors dark blue is really hard to see on a ssh terminal i know you can randomize it with R but it would be nice to be able to set a default color

**Comment by radare** [comment]
you can set that with `eco <themename>` in your radare2rc. my terminals render a proper blue, maybe you should configure it yours or use another one

also, this thing should be discussed in github issues (of r2 repo), irc or telegram, not here :)

thanks!

**Comment by wargio** [comment]
actually the color code that you will see will depend also by the terminal implementation.
the colors i have used are defined by the ANSI color table and i cannot change it.
i might add in the future a way to change them in order to avoid these issues.

**Comment by radare** [comment]
Having html output for colors would be interesting too
