### ISSUE TITLE
Fix javascript to support 64 bit addresses.

### ISSUE THREAD

**Issue by wargio** [wargio/r2dec-js#5]
Right now it only supports 53 bits addresses (which should be the max integer size of javascript)

- [x] uint64 numbers (mostly for addresses & jumps)
- [ ] Handling JSON Big Number

**Comment by radare** [comment]
We should use bignum or any uint64 implementation out there. its a pity that js doesnt supports 64bits yet, but it makes sense for a lot of optimizations sadly. Some 64bit implementations use type arrays into buffers, so they are pretty small in memory just mapping low and high 32bit words and adding an api to add/sub/mul/div/toString on them. like Frida's ptr, but fixed to 64bit.

Maybe it can be good to just use this wrapper library for all numeric operations in here. Being able to DIM a variable to a specific size can be interesting feature.

**Comment by wargio** [comment]
Agree

**Comment by wargio** [comment]
This should be handled now. the problem is now on JSON BN which are not handled.. :|

**Comment by wargio** [comment]
ok, fully supported now.
