### ISSUE TITLE
Installation issues 

### ISSUE THREAD

**Issue by Zaper1** [wargio/r2dec-js#58]
when i try to install it spits out two errors 
`core_pdd.c: In function ‘r2dec_read_file’:
core_pdd.c:33:33: error: ‘R2_HOMEDIR’ undeclared (first use in this function); did you mean ‘R2_HOME_BIN’?
  char *r2dec_home = r_str_home (R2_HOMEDIR R_SYS_DIR "r2pm" R_SYS_DIR "git" R_SYS_DIR "r2dec-js" R_SYS_DIR);`
 and 
`/usr/include/libr/r_types.h:188:19: error: expected ‘)’ before string constant
 #define R_SYS_DIR "/"` any help ?

**Comment by wargio** [comment]
Yes, sorry.
They have updated some defines and they broke r2dec.
I'm fixing it now.

**Comment by wargio** [comment]
fixed

**Comment by Zaper1** [comment]
thanks
