### ISSUE TITLE
Support for Radare2rc Config

### ISSUE THREAD

**Issue by 0xTowel** [wargio/r2dec-js#59]
Add support for  `pdd` options to be given via the `.radare2rc` file.

Example:
-  `e dec.hidecasts = true` in the rc instead of having to type `pdd --hide-casts`

**Comment by wargio** [comment]
hmm some r2 vars would be awsome..
`e r2dec.hidecasts = true`
i have to check if i'm able to add that.

**Comment by radare** [comment]
you can override the e r2dec…. command and emulate the rest of e things from that path

**Comment by wargio** [comment]
i've implemented `r2dec.hidecasts` and `r2dec.assembly` (booleans).

**Comment by radare** [comment]
What about r2dec.casts and r2dec.asm instead? Shorter, positive, one word

**Comment by wargio** [comment]
Hmmm but then I'll have to change things.. Ok

**Comment by wargio** [comment]
# Arguments

```
[0x00000c60]> pdd --help
r2dec [options]
       --help       | this help message
       --colors     | enables syntax colors
       --assembly   | shows pseudo next to the assembly
       --casts      | shows all casts in the pseudo code
       --issue      | generates the json used for the test suite
       --debug      | do not catch exceptions
       --html       | outputs html data instead of text
```

# Radare2 Evaluable vars

You can use these in your `.radare2rc` file.

```
e r2dec.casts       | shows all casts in the pseudo code
e r2dec.asm         | shows pseudo next to the assembly
e scr.html          | outputs html data instead of text
e scr.color         | enables syntax colors
```
