### ISSUE TITLE
Mode string in fopen() call is not resolved

### ISSUE THREAD

**Issue by io12** [wargio/r2dec-js#72]
```
                                             |             /* const char *mode */
    0x080489d8  push 0x8049620               |
    0x080489dd  mov eax, dword [ebx + 4]     |             eax = *(ebx + 4);
                                             |             /* const char *filename */
    0x080489e0  push eax                     |
    0x080489e1  call 0x8048880               |             eax = fopen (eax, 0x8049620);
```

In visual mode, there is a comment showing `0x8049620` as `"r"`, but the decompilation doesn't show this in the call.

Another issue is the `/* const char *mode */` doesn't refer to anything meaningful, because the `push` instruction is converted to a call further down, although, it's less clear what the expected behavior is for that issue.

The binary used is https://github.com/petroav/CMU-assembly-challenge/blob/master/binary

**Comment by radare** [comment]
Share the output of pddi

**Comment by io12** [comment]
Output of pddi: https://clbin.com/XrJNj

**Comment by wargio** [comment]
oh.. i forgot to check for strings on push.. thanks :)

**Comment by wargio** [comment]
fixed via r2
