### ISSUE TITLE
Change dereferencing of local variables

### ISSUE THREAD

**Issue by io12** [wargio/r2dec-js#82]
Right now, local variables are accessed with an asterisk. (`*(local_34h) = eax;`)

Taking the address of a variable doesn't use any dereference. (`eax = local_2ch;`)

To make the output more like C, the decompilation of the first case should be changed to `local_34h = eax;`, and the second case to `eax = &local_2ch;`

**Comment by wargio** [comment]
yes, it's true, but i do not fully support custom local vars.

**Comment by elicn** [comment]
That should go away in latest PR
