### ISSUE TITLE
3-argument function is detected as two

### ISSUE THREAD

**Issue by rfc2119** [wargio/r2dec-js#86]
This is nothing serious. The pseudo-C code for the syscall `accept` show only two arguments instead of three (the third, `socklen`, is specified in rdx). Here's the issue data from the `main` routine:
https://gist.github.com/rfc2119/26c1494d5eaccc92bbc766a185d21fe2

In the same context, the decompilation of the `setup_socket` has `htons` with 2 arguments instead of 1. Here's the issue data for the `setup_socket` function:
https://gist.github.com/rfc2119/e84855c9682db6be3dbbb2a547a4853c

Again it's nothing serious since I know already what to expect from a syscall

**Comment by elicn** [comment]
@rfc2119 could you confirm this was fixed on the latest release?
