### ISSUE TITLE
Command to dump pdd for the whole file (all functions)

### ISSUE THREAD

**Issue by Maijin** [wargio/r2dec-js#97]
Add a command to dump pdd for the whole file (all functions)

**Comment by radare** [comment]
pdd @@...

**Comment by Maijin** [comment]
Will have duplicate includes

**Comment by brainstorm** [comment]
This is a duplicate of issue #95, right?

**Comment by Maijin** [comment]
that would be really useful to mass scanning binaries and provide missing opcodes.

**Comment by wargio** [comment]
`pddf > /tmp/myfile.c`
